# Generated by Django 6.0 on 2026-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(help_text='One-two sentence summary shown on overview pages.')),
                ('motivation', models.TextField(blank=True, help_text='Why this project exists. What problem or curiosity drove it?')),
                ('challenges', models.TextField(blank=True, help_text='Key technical or conceptual challenges encountered.')),
                ('lessons_learned', models.TextField(blank=True, help_text="What you'd do differently, or what this taught you.")),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated list (e.g. Django, Postgres, dbt, AWS).', max_length=300)),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('blog_post_url', models.URLField(blank=True, help_text='Optional deep-dive writeup.')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=99, help_text='Lower values appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
