# Generated by Django 6.0 on 2026-01-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_outcome',
            field=models.TextField(blank=True, help_text='What I expected the outcome of this project to be. What did I hope to accomplish?'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('in_production', 'In Production'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='planned', help_text="The project's current status.", max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text="What I'd do differently, or what this taught me."),
        ),
    ]
