# Generated by Django 6.0 on 2026-01-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blog_post_url',
        ),
        migrations.AddField(
            model_name='project',
            name='blog_post_slug',
            field=models.TextField(blank=True, help_text='Optional deep-dive writeup (use slug from post)'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_html',
            field=models.TextField(default='fallback-value', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_outcome_html',
            field=models.TextField(default='fallback-value', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned_html',
            field=models.TextField(default='fallback-value', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='motivation_html',
            field=models.TextField(default='fallback-value', editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='[Markdown] Key technical or conceptual challenges encountered.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='expected_outcome',
            field=models.TextField(blank=True, help_text='[Markdown] What I expected the outcome of this project to be. What did I hope to accomplish?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text="[Markdown] What I'd do differently, or what this taught me."),
        ),
        migrations.AlterField(
            model_name='project',
            name='motivation',
            field=models.TextField(blank=True, help_text='[Markdown] Why this project exists. What problem or curiosity drove it?'),
        ),
    ]
