# Generated by Django 6.0 on 2026-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='debt_reported_positive',
            field=models.BooleanField(default=True, help_text="Most institutions report a debt as a positive 'amount owed'. Clear this if a liability's balance shows the wrong sign after a sync. Ignored for asset accounts."),
        ),
    ]
