# Generated by Django 6.0 on 2026-08-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_debt_reported_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='raw_content',
            field=models.TextField(blank=True, help_text="The uploaded file's text. Kept in the database rather than on disk because Heroku's filesystem is ephemeral — a dyno restart between upload and mapping would otherwise lose the file mid-wizard. It also doubles as the audit trail."),
        ),
    ]
