# Generated by Django 6.0 on 2026-08-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_importbatch_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconnection',
            name='credential_stored',
            field=models.BooleanField(default=False, editable=False, help_text='Whether access_secret holds anything. Kept in plaintext so that listing connections never has to decrypt — a lost or rotated key would otherwise take down the very page used to re-authorize.'),
        ),
    ]
