# Generated by Django 6.0 on 2026-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_backfill_credential_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='threshold_unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], help_text="Only meaningful for source-staleness alerts: the unit threshold is counted in — 'hasn't synced in more than 3 days' stores threshold=3, threshold_unit=days.", max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('account_balance', 'Account balance crosses a threshold'), ('budget_percent', 'Budget reaches a percentage'), ('budget_amount', 'Budget spend reaches an amount'), ('source_stale', "Account hasn't synced or been updated")], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='threshold',
            field=models.DecimalField(decimal_places=2, help_text='A currency amount, a percentage for budget-percent alerts, or a count of threshold_unit for source-staleness alerts.', max_digits=14),
        ),
    ]
