# Generated by Django 6.0 on 2026-08-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alert_threshold_unit_alter_alert_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('comparisons', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('key_trends', models.TextField(blank=True)),
                ('major_events', models.TextField(blank=True)),
                ('risk_areas', models.TextField(blank=True)),
                ('narrator', models.CharField(blank=True, help_text="Which narrator produced the sections above, e.g. 'openai'. Blank means none did.", max_length=40)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'constraints': [models.UniqueConstraint(fields=('year', 'quarter'), name='unique_qfr_per_quarter')],
            },
        ),
    ]
