# Generated by Django 6.0 on 2026-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_quarterlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.CharField(choices=[('david', 'David'), ('maddie', 'Maddie'), ('joint', 'Joint')], default='joint', help_text="Whose account this is — doesn't restrict who can see or edit it.", max_length=10),
        ),
        migrations.AddField(
            model_name='institution',
            name='owner',
            field=models.CharField(choices=[('david', 'David'), ('maddie', 'Maddie'), ('joint', 'Joint')], default='joint', help_text="Whose institution this is — doesn't restrict who can see or edit it.", max_length=10),
        ),
    ]
