# Generated by Django 6.0 on 2026-08-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_owner_institution_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconnection',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Optional. A connection can span several institutions, discovered automatically per account during sync — this is only a fallback, used when the provider doesn't report an institution for a given account.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='finance.institution'),
        ),
    ]
