# Generated by Django 6.0 on 2026-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_accountconnection_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='chart_sections',
            field=models.JSONField(blank=True, default=list, help_text='Charts tab section slugs, in display order.'),
        ),
    ]
