# Generated by Django 6.0 on 2026-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_userpreference_chart_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantcategorymemo',
            name='merchant_key',
            field=models.CharField(help_text='Normalized merchant string (see services.categorize).', max_length=160, unique=True),
        ),
    ]
