"""Every household view, one module per screen area, re-exported here."""

from .auth import HouseholdLoginView, HouseholdLogoutView, OTPSetupView, OTPVerifyView
from .base import HouseholdPageMixin, HouseholdView, PageTitleMixin
from .chores import (
    ChecklistView,
    ChoreCreateView,
    ChoreDeleteView,
    ChoreDetailView,
    ChoreListView,
    ChoreUpdateView,
    OccurrenceActionView,
    PartnerToggleView,
    SchedulePreviewView,
)
from .maintenance import (
    JobLinkView,
    LibraryAdoptView,
    LibraryView,
    UpkeepCreateView,
    UpkeepDeleteView,
    UpkeepDetailView,
    UpkeepListView,
    UpkeepUpdateView,
)
from .prefs import HelpView, HouseholdPreferencesView
from .projects import (
    BudgetLineCreateView,
    BudgetLineDeleteView,
    ExpenseDeleteView,
    ExpenseUpdateView,
    ProjectSpendingView,
    LinkCreateView,
    LinkDeleteView,
    MilestoneCreateView,
    MilestoneDeleteView,
    MilestoneToggleView,
    MilestoneUpdateView,
    NoteCreateView,
    NoteDeleteView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
    ProjectUpdateView,
    TaskCreateView,
    TaskUpdateView,
)
from .today import TodayView

__all__ = [
    "BudgetLineCreateView",
    "BudgetLineDeleteView",
    "ChecklistView",
    "ChoreCreateView",
    "ChoreDeleteView",
    "ChoreDetailView",
    "ChoreListView",
    "ChoreUpdateView",
    "ExpenseDeleteView",
    "ExpenseUpdateView",
    "HelpView",
    "HouseholdLoginView",
    "HouseholdLogoutView",
    "HouseholdPageMixin",
    "HouseholdPreferencesView",
    "HouseholdView",
    "JobLinkView",
    "LibraryAdoptView",
    "LibraryView",
    "LinkCreateView",
    "LinkDeleteView",
    "MilestoneCreateView",
    "MilestoneDeleteView",
    "MilestoneToggleView",
    "MilestoneUpdateView",
    "NoteCreateView",
    "NoteDeleteView",
    "OTPSetupView",
    "OTPVerifyView",
    "OccurrenceActionView",
    "PageTitleMixin",
    "PartnerToggleView",
    "ProjectCreateView",
    "ProjectDeleteView",
    "ProjectDetailView",
    "ProjectListView",
    "ProjectSpendingView",
    "ProjectUpdateView",
    "SchedulePreviewView",
    "TaskCreateView",
    "TaskUpdateView",
    "TodayView",
    "UpkeepCreateView",
    "UpkeepDeleteView",
    "UpkeepDetailView",
    "UpkeepListView",
    "UpkeepUpdateView",
]
