"""Quarterly Finance Reports.

Read-only: a QFR is generated by `manage.py generate_qfrs`, not from the UI.
Generation makes a network call and is meant to run once a quarter has
genuinely closed, which is a deliberate, occasional action — not something to
trigger accidentally from a page load.
"""

from django.views.generic import DetailView, ListView

from .access import FinanceAccessMixin
from .models import QuarterlyReport


class QFRListView(FinanceAccessMixin, ListView):
    template_name = "finance/qfr/list.html"
    context_object_name = "reports"
    model = QuarterlyReport

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "QFRs"
        return context


class QFRDetailView(FinanceAccessMixin, DetailView):
    template_name = "finance/qfr/detail.html"
    context_object_name = "report"
    model = QuarterlyReport

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = self.object.label

        metrics = self.object.metrics or {}
        context["spend_by_category"] = sorted(
            (metrics.get("spend_by_category") or {}).items(),
            key=lambda item: item[1],
            reverse=True,
        )
        context["budgets"] = metrics.get("budgets") or []

        comparisons = self.object.comparisons or {}
        context["comparisons"] = comparisons
        context["comparison_list"] = [
            comparisons[key]
            for key in ("previous_quarter", "year_ago_quarter")
            if comparisons.get(key)
        ]

        return context
