# Generated by Django 6.0 on 2026-09-30 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_rename_member_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('others_can_manage', models.BooleanField(default=False, help_text='Let the other person edit, skip, or delete this chore too.')),
                ('frequency', models.CharField(choices=[('once', "Doesn't repeat"), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=10)),
                ('starts_on', models.DateField(blank=True, help_text="For a one-off, when it's due (blank for whenever). For a repeating chore, the first due date — which also sets the weekday or day of the month it repeats on.", null=True)),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Weekly only: 0 = Monday … 6 = Sunday.')),
                ('monthly_mode', models.CharField(choices=[('day', 'On the same day of the month'), ('nth_weekday', 'On the same weekday of the month (e.g. second Saturday)'), ('last_weekday', 'On the last of that weekday (e.g. last Friday)')], default='day', max_length=15)),
                ('anchor', models.CharField(choices=[('fixed', 'On a fixed schedule'), ('after_completion', 'Counting from when it was last done')], default='fixed', max_length=20)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text="One-off only: the hard 'must be done by'.", null=True)),
                ('deadline_offset_days', models.PositiveSmallIntegerField(blank=True, help_text='Repeating only: each occurrence must be done within this many days of its due date.', null=True)),
                ('season_start_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('season_end_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Whose checklist it appears on. Empty means either of you.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chores', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Who controls it. Empty means the household owns it — shared work either of you can manage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_chores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_on', models.DateField(blank=True, help_text='Empty for a one-off due whenever.', null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'To do'), ('done', 'Done'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='open', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='household.chore')),
                ('completed_by', models.ForeignKey(blank=True, help_text='Who actually did it — not necessarily the assignee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('due_on'), nulls_last=True), 'id'],
                'indexes': [models.Index(fields=['status', 'due_on'], name='household_o_status_7bbf84_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('chore',), name='one_open_occurrence_per_chore')],
            },
        ),
    ]
