# Generated by Django 6.0 on 2026-09-30 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_chores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_partner_chores', models.BooleanField(default=False, help_text="Show the other person's chores alongside your own.")),
                ('share_new_chores', models.BooleanField(default=False, help_text='Let the other person manage new chores you create, unless you say otherwise.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
