# Generated by Django 6.0 on 2026-09-30 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_household_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What doing it cost, as a positive number — mostly for maintenance.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('hvac', 'Heating & cooling'), ('plumbing', 'Plumbing & water'), ('electrical', 'Electrical'), ('safety', 'Safety'), ('appliances', 'Appliances'), ('exterior', 'Exterior & roof'), ('yard', 'Yard & garden'), ('cleaning', 'Deep cleaning'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Where in the house — "basement furnace".', max_length=120)),
                ('instructions', models.TextField(blank=True, help_text='How to do it, for whichever of you does it next.')),
                ('supplies', models.TextField(blank=True, help_text='What it needs — "16x25x1 MERV 11 filter".')),
                ('supply_url', models.URLField(blank=True, help_text='Where to buy them.')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='What it usually costs each time, as a positive number.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('chore', models.OneToOneField(help_text="Carries the schedule, whose list it's on, and the history.", on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_item', to='household.chore')),
            ],
            options={
                'ordering': ['area', 'chore__title'],
            },
        ),
    ]
