# Generated by Django 6.0 on 2026-09-30 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_merchantcategorymemo_merchant_key'),
        ('household', '0005_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text="The purchase this job's cost came from, when linked.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction'),
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('estimated', models.DecimalField(decimal_places=2, help_text='As a positive number.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='household.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='household.budgetline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='household.project')),
                ('transaction', models.ForeignKey(help_text="Deleted with the transaction: an expense that no longer exists isn't spending.", on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.transaction')),
            ],
            options={
                'ordering': ['-transaction__posted_on', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'transaction'), name='one_link_per_project_transaction')],
            },
        ),
    ]
