# Generated by Django 6.0 on 2026-09-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_finance_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdpreference',
            name='last_digest_on',
            field=models.DateField(blank=True, help_text='The household date the last digest went out — what keeps it to one a morning.', null=True),
        ),
        migrations.AddField(
            model_name='householdpreference',
            name='morning_digest',
            field=models.BooleanField(default=False, help_text="Email me a morning summary: overdue and today's chores, the week ahead, and project milestones."),
        ),
    ]
