# Generated by Django 6.0 on 2026-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_digest_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='schedule_set_on',
            field=models.DateField(blank=True, help_text='The household date the schedule was last set or changed. An occurrence limit counts from here: changing the schedule restarts it.', null=True),
        ),
    ]
