# Generated by Django 6.0 on 2026-10-01 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_merchantcategorymemo_merchant_key'),
        ('household', '0008_schedule_set_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('transaction',), name='one_job_per_transaction'),
        ),
    ]
